name: build AntWars
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: AntWars-jar
          path: build/libs/*.jar
